IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('UserTest'))
BEGIN;
    DROP TABLE [UserTest];
END;
GO

CREATE TABLE [UserTest] (
    [UserTestID] INTEGER NOT NULL IDENTITY(1, 1),
    [id] INTEGER NULL,
    [name] VARCHAR(255) NULL,
    [email] VARCHAR(255) NULL,
    [password] VARCHAR(255) NULL,
    PRIMARY KEY ([UserTestID])
);
GO

INSERT INTO UserTest([id],[name],[email],[password]) VALUES(1,'Flynn','tellus.Suspendisse@tempus.net','GDB31HZE5FR'),(2,'Louis','sapien.cursus@sit.org','RCD90TBG7ZY'),(3,'Alan','gravida@sit.co.uk','NBD68VDV7TC'),(4,'Thaddeus','egestas.rhoncus@nec.net','ZGA19IBC1FS'),(5,'Brennan','lorem@Duis.co.uk','MSU46TGW1XF'),(6,'Abbot','Suspendisse@convallis.com','QXT86GKL3MB'),(7,'Jonah','pharetra.felis@eleifend.net','ETX05MYA4QG'),(8,'Hasad','dictum.mi.ac@nequeNullam.co.uk','SHV64KYY6NN'),(9,'Nathaniel','tincidunt.neque.vitae@luctusaliquetodio.ca','BNE69GXB0SX'),(10,'Baker','risus@velitegestaslacinia.edu','BRL11OFE7HR');
INSERT INTO UserTest([id],[name],[email],[password]) VALUES(11,'Cedric','natoque@vel.edu','YHJ36OHT2RL'),(12,'Ahmed','neque@cursus.co.uk','RFV04NGA2DP'),(13,'Xenos','nulla.In@maurisidsapien.edu','ITS27SVX4LM'),(14,'Edan','urna@eumetus.co.uk','RVE33PCW1XT'),(15,'Jesse','non.nisi.Aenean@ligula.net','QMN81VGA6OI'),(16,'Hamilton','sodales.elit@semper.net','EIL61CDD6HU'),(17,'Keith','in.felis.Nulla@Vivamuseuismodurna.edu','GQX80FNY7VA'),(18,'Kirk','vel.arcu.eu@enimnislelementum.com','WQR72FVG3FM'),(19,'Carlos','primis.in.faucibus@enimSuspendisse.net','IHT34QWN8SE'),(20,'Hop','quam.a.felis@nequeMorbi.ca','HVY38YZP3EL');
INSERT INTO UserTest([id],[name],[email],[password]) VALUES(21,'Carter','sed@posuere.net','MUY31VUO4GX'),(22,'Erich','accumsan.interdum@interdumenimnon.org','ERS70YJL5XM'),(23,'Herman','libero.Morbi@nonnisi.co.uk','ZEE56CLE0EY'),(24,'Kuame','sed.pede@Sed.com','WLL30YRY8WC'),(25,'Mannix','nulla.In@liberoatauctor.ca','FHD87SMU7QC'),(26,'Hamilton','aliquam.eu@imperdietnec.ca','LZK38LFY3GQ'),(27,'Price','sagittis.felis@risusMorbi.co.uk','OCB53ZCN4EM'),(28,'Jonah','diam.luctus@elementum.edu','BPD29GFN5FS'),(29,'Wade','est@anteblanditviverra.org','RSF74KWJ9NM'),(30,'Valentine','primis.in.faucibus@in.org','OZF63XYR6TH');
INSERT INTO UserTest([id],[name],[email],[password]) VALUES(31,'Bradley','Mauris.vel@elitNullafacilisi.net','LLR68ZJO6WT'),(32,'Wade','arcu.Curabitur.ut@mitempor.edu','IPR96OTD4WT'),(33,'Scott','Vestibulum.ante@lobortistellusjusto.ca','XYC23HUA7LM'),(34,'Jermaine','erat.in@convallis.ca','OMF53ONO3OE'),(35,'Tate','elit.dictum.eu@iaculis.edu','DUZ72FZT8UZ'),(36,'Eric','sodales.elit@semconsequatnec.com','XHA66PCT8PO'),(37,'Kieran','tristique.ac@euduiCum.com','QIF40WTE5RJ'),(38,'Kasper','erat@cursus.co.uk','OZN10BYG0BP'),(39,'Adam','lorem.vehicula.et@eunibhvulputate.net','EGL96CUH7LK'),(40,'Dalton','porttitor.tellus.non@Namconsequat.net','LPU41CRP0FG');
INSERT INTO UserTest([id],[name],[email],[password]) VALUES(41,'Hasad','dolor.Nulla.semper@Suspendissealiquet.co.uk','BUN96WTV5ZR'),(42,'Raymond','tempus.mauris.erat@ultrices.co.uk','AJV56PRV9MT'),(43,'Garrett','auctor.odio@euismodac.org','QME23UOL7VF'),(44,'Edward','id@nequeSed.org','ROA60RBB9JU'),(45,'Ahmed','amet.risus@ipsum.org','QXI66LLU1KU'),(46,'Edan','congue.a.aliquet@purus.edu','DML19DXA8FS'),(47,'Aquila','risus@nuncsedpede.net','MVP54LNW8DO'),(48,'Boris','et.commodo.at@Praesent.net','XBI80MWL4OS'),(49,'Steven','Cras.vehicula@eu.co.uk','VRA61EHI5HK'),(50,'Reed','gravida@tristiquesenectus.ca','CDP52MQV1AM');
INSERT INTO UserTest([id],[name],[email],[password]) VALUES(51,'Brennan','ultrices.a@musDonec.ca','FPZ54EJS5XD'),(52,'Malachi','malesuada@facilisismagnatellus.edu','MXS07NCB8AG'),(53,'Herman','faucibus.ut@Suspendisseseddolor.org','KTY33VKB6IZ'),(54,'Ethan','tempor.lorem@sociisnatoquepenatibus.net','XOJ85TUW8SL'),(55,'Phillip','mus.Aenean.eget@Nuncullamcorper.co.uk','WWR57EOX0UC'),(56,'Griffin','adipiscing.elit.Etiam@loremluctus.org','LUU57HCN9DQ'),(57,'Talon','sed@diamProin.com','CPO45BYA5YN'),(58,'Ezra','Nullam.ut.nisi@risus.com','YKA88LHR5PN'),(59,'Blaze','vulputate.eu@dictumplacerat.com','LHH54DWI6GH'),(60,'Perry','eu.elit@idblanditat.ca','JCH53VSB9MS');
INSERT INTO UserTest([id],[name],[email],[password]) VALUES(61,'Zachary','Cras.interdum.Nunc@Suspendissealiquetmolestie.edu','JQS06TEE6MY'),(62,'Ahmed','consectetuer.cursus.et@nulla.com','ZPB85RQX6KJ'),(63,'Neil','sapien.Nunc.pulvinar@aenimSuspendisse.edu','EDI17DTS5OX'),(64,'Emerson','pellentesque.tellus@faucibus.edu','RTU46VZZ9LG'),(65,'Phelan','consequat.purus.Maecenas@ategestasa.co.uk','EPX85XIG3FC'),(66,'Ulric','a.enim.Suspendisse@imperdiet.org','CWV06BKH3TL'),(67,'Harrison','Aenean.eget.magna@inconsequat.org','FSM35GJM6SV'),(68,'Quinn','libero@Sed.co.uk','BPO21XWV1XB'),(69,'Jarrod','orci@telluslorem.org','JOD70REN2CT'),(70,'Thane','risus.Duis@Donecelementum.org','JOE80AAK7OM');
INSERT INTO UserTest([id],[name],[email],[password]) VALUES(71,'Orson','lacinia.mattis@amagna.org','KZH71JFP5AM'),(72,'Griffith','id.libero@telluseuaugue.org','TFW90RXL9HP'),(73,'Tanek','senectus.et.netus@Vivamussit.com','QED80PCI3ZK'),(74,'Timothy','non@Etiamimperdiet.co.uk','OBB57RVE3HW'),(75,'Aladdin','lorem.ac.risus@Suspendissenonleo.ca','MNL45XFG8GF'),(76,'Colin','odio.sagittis.semper@quismassa.net','TRM26AHK1WS'),(77,'Brock','Curabitur@vitaeposuere.net','UZE43GNV2BE'),(78,'Keefe','taciti.sociosqu.ad@mollisnec.org','VHX11PNJ8VB'),(79,'Reese','feugiat.placerat@tellus.ca','DON45QCK5ZP'),(80,'Jesse','ac.sem.ut@malesuada.co.uk','WVZ55YWC1HN');
INSERT INTO UserTest([id],[name],[email],[password]) VALUES(81,'Neville','in.faucibus@morbitristique.org','RHG34ZHL0UT'),(82,'Ciaran','Curabitur.ut.odio@adipiscing.edu','OMT96YFK1NV'),(83,'Avram','Mauris@Vestibulumut.org','SHV11KAT1DR'),(84,'Mohammad','aptent@porttitortellus.net','ITS50BOP0YP'),(85,'Burke','vulputate.eu@dolor.ca','ZWO29HTU1NU'),(86,'Vaughan','dui.semper@anteVivamusnon.ca','SUA40EPJ8WC'),(87,'Baker','aliquam.enim.nec@pede.ca','HSU58WRV3LR'),(88,'Peter','faucibus.lectus.a@quislectus.com','WOJ32PVH5WF'),(89,'Denton','ac.mi.eleifend@Ut.edu','TCJ78MCG3HZ'),(90,'Allen','nulla.magna.malesuada@tortor.net','ZFQ66PKU1HB');
INSERT INTO UserTest([id],[name],[email],[password]) VALUES(91,'Carson','risus.In.mi@dapibusid.net','ZIB48MKV7GA'),(92,'Neil','vitae.odio.sagittis@Nullamsuscipitest.co.uk','MXF88BZI6CV'),(93,'Kasimir','vel.sapien@CuraeDonec.net','PTR43NQW5RD'),(94,'Axel','Aliquam.ornare.libero@vitaepurusgravida.co.uk','KLA48QGZ6HF'),(95,'Beau','tempus.mauris.erat@velitCraslorem.edu','YEL47OQH9XT'),(96,'Tucker','sed.est@anteblandit.edu','PQC86QQU3SL'),(97,'Ivor','tristique.senectus@Sed.edu','UPQ20FSM5JZ'),(98,'Burton','amet@velit.net','CTS37WGO8VE'),(99,'Beau','Suspendisse.sagittis@liberolacusvarius.ca','QOE54TCF4NB'),(100,'Ishmael','nonummy.ipsum@lobortisquam.ca','QIW88NMD3RT');
