-- **************************************************************************
-- * Script para gerar a base de dados da aplicação Modelo, com foco no DDD *
-- *                  Asp.Net Core 3.1, mysql, Web.Api                      *
-- **************************************************************************

DROP TABLE `user`;

CREATE TABLE `user` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `id` mediumint,
  `name` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  `password` varchar(255),
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `user` (`id`,`name`,`email`,`password`) VALUES (1,"Kasper","sed@turpis.org","MYE06QCH8OE"),(2,"Martin","non.lorem@rutrumFusce.com","RLU01QMW6DQ"),(3,"Macon","Phasellus.libero@ornaresagittis.com","VGV92FNQ0WD"),(4,"Amir","neque@orci.ca","QVK05MEB6KM"),(5,"Lance","ac.urna@dictum.com","FOO15OFG9KO"),(6,"Slade","pede@enimnec.com","QUA46FVZ9ML"),(7,"Bernard","magna.a.neque@dolorsitamet.org","ZOS97SOH1NB"),(8,"Forrest","sit@estmaurisrhoncus.net","TWY61GEL1JZ"),(9,"Zahir","Duis@sodalesnisi.co.uk","CBF78KGK6TR"),(10,"Justin","Nullam.ut.nisi@ligulaAliquamerat.co.uk","TQS23GJY5PB");
INSERT INTO `user` (`id`,`name`,`email`,`password`) VALUES (11,"Dean","sodales@commodo.ca","REW20BIA3KG"),(12,"Arsenio","natoque.penatibus@enimEtiamimperdiet.ca","OGB29PWZ9NB"),(13,"Erich","mauris.ut.mi@dolor.ca","EFI37YXN7AW"),(14,"Eagan","fringilla.est@tortordictum.org","EMH57QHS7OA"),(15,"Elvis","sapien.Nunc@pharetra.edu","LLW54PJL8EP"),(16,"Joshua","elit.Aliquam.auctor@tellus.com","FQN91NMF4HO"),(17,"Marsden","elit.elit.fermentum@semPellentesque.edu","QNY35HHD4PR"),(18,"Aquila","orci.Ut.semper@egetmetuseu.com","ZAK05OQL0NT"),(19,"Linus","neque.Sed@etcommodoat.co.uk","VHG02BOM0WN"),(20,"Cooper","nunc@nonsollicitudina.ca","SJR25TSB4XL");
INSERT INTO `user` (`id`,`name`,`email`,`password`) VALUES (21,"Dolan","sit.amet.risus@tempusscelerisquelorem.ca","TXZ07SQV0XO"),(22,"David","euismod@hendreritDonecporttitor.org","RAR59VAB8PF"),(23,"Wang","tempus.eu@habitantmorbi.co.uk","RWF89IYS1NC"),(24,"Shad","habitant.morbi.tristique@MorbivehiculaPellentesque.edu","ERB87BQB4NZ"),(25,"Lester","urna.justo@ante.ca","BPY54GYN8LH"),(26,"Daquan","Duis.volutpat@dui.com","KTC34WZL1NR"),(27,"Clayton","neque@Nullamfeugiat.ca","LWM35QBQ7QU"),(28,"Dane","imperdiet@Phasellusliberomauris.net","PSN51SBP5DQ"),(29,"Wang","a@volutpatnuncsit.net","KMZ40TAS0HI"),(30,"Caleb","et.netus.et@Fuscefermentum.org","QLK98VCF8FL");
INSERT INTO `user` (`id`,`name`,`email`,`password`) VALUES (31,"Xenos","lobortis@erosturpis.org","NUM49FBM9LB"),(32,"Hayes","facilisis.facilisis@placerategetvenenatis.net","LCP68VFB7FQ"),(33,"Ignatius","dolor.Fusce.feugiat@estac.org","IFX68ROE2ZJ"),(34,"Keane","elementum.dui@elita.org","NMJ74LWH3HN"),(35,"Jerry","pede.blandit.congue@urnajustofaucibus.com","MFC13XTB0VM"),(36,"Cody","consequat@hendreritDonec.edu","GTF69ODG5OF"),(37,"Maxwell","sit@eu.com","JPK13ULV6SP"),(38,"Moses","augue.id@vulputateullamcorper.com","UAQ80VLS8EP"),(39,"Dylan","eget.magna.Suspendisse@convallis.com","LJE03EHM2NQ"),(40,"Alfonso","lacus.Ut.nec@Donec.com","PUZ28PDG7AX");
INSERT INTO `user` (`id`,`name`,`email`,`password`) VALUES (41,"Ross","dapibus@dolor.co.uk","NNY74NJF3DH"),(42,"Keaton","orci.adipiscing@eleifendvitae.ca","GMH02KLI5MS"),(43,"Lane","Pellentesque.tincidunt.tempus@Phasellus.edu","SWA47OUS3NL"),(44,"Harlan","Donec.egestas@ipsumSuspendisse.co.uk","MYJ37YYC4QE"),(45,"Stewart","amet.consectetuer.adipiscing@utodio.org","EZT37FHK3BZ"),(46,"Salvador","tincidunt@morbitristique.net","NTH11ALE1OW"),(47,"Alan","Donec@scelerisquenequeNullam.ca","PUU81JUU0DS"),(48,"Adrian","vitae.erat@ipsum.net","TXY12NIW5HW"),(49,"Alec","ornare.Fusce.mollis@cursuset.co.uk","CIB09KZG8JR"),(50,"Ahmed","senectus.et.netus@etarcu.net","JGQ96QXT8VG");
INSERT INTO `user` (`id`,`name`,`email`,`password`) VALUES (51,"Tobias","eu@quisdiamPellentesque.org","EKM82JDI6SC"),(52,"Dane","vitae.erat.vel@magnisdisparturient.net","JOB70WVM8CE"),(53,"Vaughan","leo.Cras.vehicula@Aliquamornare.ca","TVP43QEE8DX"),(54,"Richard","vestibulum.neque@Maecenas.com","UFD19GOE2SM"),(55,"Vernon","Aliquam.tincidunt@pedeetrisus.com","SMY83ZWO5SP"),(56,"Martin","ipsum.cursus@ante.org","RKX70IWD6FX"),(57,"Sebastian","dolor.elit@semmolestiesodales.org","DOH14PIL9TE"),(58,"Branden","amet.ante@Seddictum.ca","KEL85NKZ2MJ"),(59,"Harrison","pede.ultrices.a@magnaNamligula.ca","HYG25IUB1RT"),(60,"James","Phasellus@dolorsitamet.org","VFC00ZJF1OT");
INSERT INTO `user` (`id`,`name`,`email`,`password`) VALUES (61,"Lionel","nisi@arcu.ca","YAD52BFH4UG"),(62,"Elvis","mauris@Aliquamerat.net","QFF62UUK6XQ"),(63,"Brian","aliquet@convalliserat.com","PUS94FHF5AN"),(64,"David","Fusce.aliquet.magna@etmagnisdis.net","FSP88KIA2DL"),(65,"Silas","Curabitur@nuncinterdum.edu","KWH09BSU9PI"),(66,"Hedley","adipiscing.enim.mi@sedfacilisisvitae.net","WSS48RJD4VX"),(67,"Xavier","lacus.Nulla@natoquepenatibus.com","DNG51LUY7DC"),(68,"Bevis","lacinia.vitae@purusDuis.ca","PNX67CQM4OX"),(69,"Trevor","fames.ac@dignissimlacusAliquam.org","TLA32BCL2DC"),(70,"Yardley","tincidunt.vehicula.risus@Aliquam.edu","WIA71XOA6DW");
INSERT INTO `user` (`id`,`name`,`email`,`password`) VALUES (71,"Yoshio","aliquet.molestie.tellus@lacusNullatincidunt.co.uk","SND62UEC2GF"),(72,"Barrett","eget.nisi@quis.edu","GAG92ZGU6CK"),(73,"Judah","Proin@erosProinultrices.net","BGT42MYK2OZ"),(74,"Colton","non@sedconsequatauctor.ca","NIY09FWN5PN"),(75,"Abel","egestas.a@fermentum.com","EBE32IFK8EO"),(76,"Lucian","Morbi.non.sapien@uterat.co.uk","SUW73RZP7LO"),(77,"Darius","Fusce.aliquet@nectellus.com","SIQ37GTH9NQ"),(78,"Ignatius","urna.nec.luctus@tempor.ca","FMH56KON4TO"),(79,"Dennis","risus.Quisque@enimNunc.org","VHB18BRH4CU"),(80,"Melvin","vulputate.nisi@Fuscealiquet.net","VEN44OCF4IU");
INSERT INTO `user` (`id`,`name`,`email`,`password`) VALUES (81,"Chester","semper@placerateget.ca","DTO50NWZ4JU"),(82,"Palmer","sit.amet@penatibus.co.uk","PGL77XCH3TT"),(83,"Arden","ridiculus.mus.Proin@facilisisloremtristique.org","JVG04AWJ1CF"),(84,"Dominic","quis.diam@sociosqu.ca","SSA01RQJ4CW"),(85,"Jerry","elit.Nulla.facilisi@convallis.edu","MDX83GMD3CE"),(86,"Brennan","et.pede.Nunc@elementum.ca","XVR19QZL5VI"),(87,"Harlan","porta.elit.a@sedleoCras.edu","RED05LMA4ZT"),(88,"Elliott","aliquet@ante.edu","ZFN49VQL8AJ"),(89,"Yasir","netus.et.malesuada@quisturpis.org","WOU04VLZ5FT"),(90,"Vernon","risus@luctuset.net","SJF13JWZ0DX");
INSERT INTO `user` (`id`,`name`,`email`,`password`) VALUES (91,"Jakeem","lobortis@imperdietdictum.co.uk","UET31CIQ7OQ"),(92,"Chester","sollicitudin.a.malesuada@ac.com","FWY75HYH7YN"),(93,"Anthony","Integer.vulputate.risus@metus.org","WGC50VTN7AI"),(94,"Buckminster","mi.lacinia.mattis@mauris.com","TYG10EIY3FE"),(95,"Mohammad","magna@tortorIntegeraliquam.ca","JKY09DCO8KF"),(96,"Calvin","enim.nec@nequepellentesque.net","CPC67TPC5MP"),(97,"Reuben","eget.metus.In@semNullainterdum.org","PYC11YPS7XN"),(98,"Clarke","Nunc.mauris.Morbi@ligulaelitpretium.org","ITH89ADA9OK"),(99,"Alfonso","amet@est.edu","WDB31UFV1NG"),(100,"Aaron","nec.orci.Donec@Aeneangravida.ca","UOL22PVD7DO");
